version: '3.7'

services:
  tww_rando_bot:
    image: tww_rando_bot
    build:
      context: .
    command: randobot ${GITHUB_TOKEN} ${CATEGORY_SLUG-twwr} ${CLIENT_ID} ${CLIENT_SECRET} --verbose
    restart: always
    ulimits:
      core:
        hard: 0
        soft: 0
    volumes:
      - .:/tww-rando-bot
      - egg_info:/tww-rando-bot/tww_rando_bot.egg-info

volumes:
  egg_info:
    name: egg_info
